#!/usr/bin/env bash
#MISE description="Security check (gitleaks + grype)"

#USAGE flag "--debug" help="emit debug logs"

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/helpers"

print_header "Scanning files using grype (${MISE_PROJECT_ROOT}) ..."
[[ "${usage_debug:-false}" == "true" ]] && FLAGS="-vv" || FLAGS=""
grype . --config .config/grype.yaml --name ${MISE_PROJECT_ROOT} ${FLAGS}

print_header "Run gitleaks on $PWD ..."
[[ "${usage_debug:-false}" == "true" ]] && FLAGS="--verbose" || FLAGS=""
gitleaks dir ${PWD} --config $MISE_PROJECT_ROOT/.config/gitleaks.toml --redact 50 ${FLAGS}

print_header "Scanning done"
