#!/usr/bin/env bash
#MISE description="Run pnpm audit"
#MISE hide=false

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

print_header "Run pnpm audit on packages ..."
pnpm audit --reporter=summary

print_header "pnpm audit complete!"
