#!/usr/bin/env bash
#MISE description="Setup Doppler for local development"
#MISE hide=false

set -e
source "${MISE_PROJECT_ROOT}/.config/mise/tasks/_scripts/_helpers"

# print_header "Setting up Doppler (service) ..."
# mise x --cd "${MISE_PROJECT_ROOT}/backend/projects/service" -- doppler setup --no-interactive --no-read-env --project "service" --config "dev"
