min_version = "2026.10.0"

[settings]
activate_aggressive  = true
all_compile          = false
env_shell_expand     = true
gpg_verify           = true
raw                  = true
status.missing_tools = "always"

# Tools will auto install if task needs them
task.run_auto_install = true
